# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.type_info_metadata import TypeInfoMetadata

class TestTypeInfoMetadata(unittest.TestCase):
    """TypeInfoMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypeInfoMetadata:
        """Test TypeInfoMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypeInfoMetadata`
        """
        model = TypeInfoMetadata()
        if include_optional:
            return TypeInfoMetadata(
                array_v2 = openapi_client.models.type_array_v2_metadata.TypeArrayV2Metadata(
                    elements = [
                        openapi_client.models.array_v2_element_metadata.ArrayV2ElementMetadata(
                            id = '', 
                            type = '', )
                        ], ),
                int = openapi_client.models.type_int_metadata.TypeIntMetadata(
                    max_value = 56, 
                    min_value = 56, ),
                media = openapi_client.models.type_media_metadata.TypeMediaMetadata(
                    track_id = '', 
                    track_type = '', ),
                string = openapi_client.models.type_string_metadata.TypeStringMetadata(
                    charset = '', 
                    max_length = 56, 
                    min_length = 56, )
            )
        else:
            return TypeInfoMetadata(
        )
        """

    def testTypeInfoMetadata(self):
        """Test TypeInfoMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
