# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_v2_sessions_get200_response_one_of import ApiV2SessionsGet200ResponseOneOf

class TestApiV2SessionsGet200ResponseOneOf(unittest.TestCase):
    """ApiV2SessionsGet200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2SessionsGet200ResponseOneOf:
        """Test ApiV2SessionsGet200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2SessionsGet200ResponseOneOf`
        """
        model = ApiV2SessionsGet200ResponseOneOf()
        if include_optional:
            return ApiV2SessionsGet200ResponseOneOf(
                data = [
                    openapi_client.models.session.Session(
                        application = '', 
                        config = null, 
                        config_name = '', 
                        config_url = '', 
                        created = 56, 
                        data_model_url = '', 
                        id = '', 
                        index = 56, 
                        last_visited = 56, 
                        meta = [
                            openapi_client.models.pair.Pair(
                                id = 56, 
                                key = '', 
                                value = '', )
                            ], 
                        name = '', 
                        owner = '', 
                        owner_id = '', 
                        pinned = True, 
                        state = '', 
                        test = openapi_client.models.test_info.TestInfo(
                            dashboards = [
                                openapi_client.models.dashboard.Dashboard(
                                    id = '', 
                                    name = '', )
                                ], 
                            default_dashboard_index = 56, 
                            default_polling_interval = 56, 
                            status = '', 
                            test_details = '', 
                            test_duration = 56, 
                            test_elapsed = 56, 
                            test_id = '', 
                            test_initialized = 56, 
                            test_started = 56, 
                            test_stopped = 56, ), )
                    ],
                total_count = 56
            )
        else:
            return ApiV2SessionsGet200ResponseOneOf(
        )
        """

    def testApiV2SessionsGet200ResponseOneOf(self):
        """Test ApiV2SessionsGet200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
