# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pfs_p2_group import PfsP2Group

class TestPfsP2Group(unittest.TestCase):
    """PfsP2Group unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPfsP2Group(self):
        """Test PfsP2Group"""
        # inst = PfsP2Group()

if __name__ == '__main__':
    unittest.main()
