# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from cyperf.models.api_v2_appsec_ui_metadata_get200_response_one_of import ApiV2AppsecUiMetadataGet200ResponseOneOf
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

APIV2APPSECUIMETADATAGET200RESPONSE_ONE_OF_SCHEMAS = ["ApiV2AppsecUiMetadataGet200ResponseOneOf"]

class ApiV2AppsecUiMetadataGet200Response(BaseModel):
    """
    ApiV2AppsecUiMetadataGet200Response
    """
    # data type: ApiV2AppsecUiMetadataGet200ResponseOneOf
    oneof_schema_1_validator: Optional[ApiV2AppsecUiMetadataGet200ResponseOneOf] = None
    actual_instance: Optional[Union[ApiV2AppsecUiMetadataGet200ResponseOneOf]] = None
    one_of_schemas: Set[str] = { "ApiV2AppsecUiMetadataGet200ResponseOneOf" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ApiV2AppsecUiMetadataGet200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: ApiV2AppsecUiMetadataGet200ResponseOneOf
        if not isinstance(v, ApiV2AppsecUiMetadataGet200ResponseOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ApiV2AppsecUiMetadataGet200ResponseOneOf`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ApiV2AppsecUiMetadataGet200Response with oneOf schemas: ApiV2AppsecUiMetadataGet200ResponseOneOf. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ApiV2AppsecUiMetadataGet200Response with oneOf schemas: ApiV2AppsecUiMetadataGet200ResponseOneOf. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ApiV2AppsecUiMetadataGet200ResponseOneOf
        try:
            instance.actual_instance = ApiV2AppsecUiMetadataGet200ResponseOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ApiV2AppsecUiMetadataGet200Response with oneOf schemas: ApiV2AppsecUiMetadataGet200ResponseOneOf. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ApiV2AppsecUiMetadataGet200Response with oneOf schemas: ApiV2AppsecUiMetadataGet200ResponseOneOf. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ApiV2AppsecUiMetadataGet200ResponseOneOf]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


