# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.exchange_payload import ExchangePayload
from cyperf.models.generic_file import GenericFile
from typing import Optional, Set, Union, GenericAlias, get_args
from typing_extensions import Self
from pydantic import Field
#from cyperf.models import LinkNameException

if "AppExchange" != "APILink":
    from cyperf.models.api_link import APILink

class AppExchange(BaseModel):
    """
    AppExchange
    """ # noqa: E501
    c2s_payload: Optional[GenericFile] = Field(default=None, alias="c2sPayload")
    id: Optional[StrictStr] = None
    payload: Optional[ExchangePayload] = None
    s2c_payload: Optional[GenericFile] = Field(default=None, alias="s2cPayload")
    links: Optional[List[APILink]] = Field(default=None, description="Links to other properties")
#    api_client: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["c2sPayload", "id", "payload", "s2cPayload"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


#    @property
#    def rest_c2s_payload(self):
#        if self.c2s_payload is not None:
#            return self.c2s_payload
#        field_info = self.__class__.__fields__["c2s_payload"]
#        try:
#            self.c2s_payload =  self.link_based_request(field_info.alias, "GET", return_type="GenericFile")
#        except LinkNameException as e:
#            self.c2s_payload =  self.link_based_request("c2s_payload", "GET", return_type="GenericFile")
#        return self.c2s_payload
#
#    @rest_c2s_payload.setter
#    def rest_c2s_payload(self, value):
#        self.c2s_payload = value

#    @property
#    def rest_id(self):
#        if self.id is not None:
#            return self.id
#        field_info = self.__class__.__fields__["id"]
#        try:
#            self.id =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.id =  self.link_based_request("id", "GET", return_type="str")
#        return self.id
#
#    @rest_id.setter
#    def rest_id(self, value):
#        self.id = value

#    @property
#    def rest_payload(self):
#        if self.payload is not None:
#            return self.payload
#        field_info = self.__class__.__fields__["payload"]
#        try:
#            self.payload =  self.link_based_request(field_info.alias, "GET", return_type="ExchangePayload")
#        except LinkNameException as e:
#            self.payload =  self.link_based_request("payload", "GET", return_type="ExchangePayload")
#        return self.payload
#
#    @rest_payload.setter
#    def rest_payload(self, value):
#        self.payload = value

#    @property
#    def rest_s2c_payload(self):
#        if self.s2c_payload is not None:
#            return self.s2c_payload
#        field_info = self.__class__.__fields__["s2c_payload"]
#        try:
#            self.s2c_payload =  self.link_based_request(field_info.alias, "GET", return_type="GenericFile")
#        except LinkNameException as e:
#            self.s2c_payload =  self.link_based_request("s2c_payload", "GET", return_type="GenericFile")
#        return self.s2c_payload
#
#    @rest_s2c_payload.setter
#    def rest_s2c_payload(self, value):
#        self.s2c_payload = value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppExchange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of c2s_payload
        if self.c2s_payload:
            _dict['c2sPayload'] = self.c2s_payload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payload
        if self.payload:
            _dict['payload'] = self.payload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of s2c_payload
        if self.s2c_payload:
            _dict['s2cPayload'] = self.s2c_payload.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppExchange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "c2sPayload": GenericFile.from_dict(obj["c2sPayload"]) if obj.get("c2sPayload") is not None else None,
                        "id": obj.get("id"),
                        "payload": ExchangePayload.from_dict(obj["payload"]) if obj.get("payload") is not None else None,
                        "s2cPayload": GenericFile.from_dict(obj["s2cPayload"]) if obj.get("s2cPayload") is not None else None
            ,
            "links": obj.get("links")
        })
#        _obj.api_client = client
        return _obj

#    def update(self):
#        self.link_request("self", "PUT", body=self)
#
#   def link_based_request(self, link_name, method, return_type = None, body = None):
#        if self.links == None:
#           raise Exception("You must allow links to be present to use automatic retrieval functions.")
#        if link_name == 'self':
#            self_links = [link for link in self.links if link.rel == link_name]
#        else:
#            self_links = [link for link in self.links if link.rel == "child" and link.name == link_name]
#        if len(self_links) == 0:
#           raise LinkNameException(f"Missing {link_name} link.")
#        self_link = self_links[0]
#        
#        _host = None
#
#        _collection_formats: Dict[str, str] = {
#        }#
#
#        _path_params: Dict[str, str] = {}
#        _query_params: List[Tuple[str, str]] = []
#        _header_params: Dict[str, Optional[str]] = {}
#        _form_params: List[Tuple[str, str]] = []
#        _files: Dict[str, Union[str, bytes]] = {}
#        _body_params: Optional[bytes] = None
#        if body:
#            _body_params = body.to_json().encode('utf-8')
#
#        # set the HTTP header `Accept`
#        if 'Accept' not in _header_params:
#            _header_params['Accept'] = self.api_client.select_header_accept(
#                [
#                    'application/json'
#                ]
#            )
#        if 'Content-Type' not in _header_params:
#            _header_params['Content-Type'] = self.api_client.select_header_content_type(
#                [
#                    'application/json'
#                ]
#            )
#        _auth_settings: List[str] = [
#            'OAuth2',
#        ]
#        _param = self.api_client.param_serialize(
#            method=method,
#           resource_path=self_link.href,
#            path_params=_path_params,
#           query_params=_query_params,
#           body=_body_params,
#            post_params=_form_params,
#            files=_files,
#            auth_settings=_auth_settings,
#            collection_formats=_collection_formats,
#            _host=_host
#        )
#        response_data = self.api_client.call_api(
#            *_param
#        )
#        response_data.read()
#        response_types = {
#            '200': return_type,
#            '500': 'ErrorResponse'
#        }
#        return self.api_client.response_deserialize(response_data, response_types).data
    


