# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from cyperf.models.counted_feature_consumer import CountedFeatureConsumer
from typing import Optional, Set, Union, GenericAlias, get_args
from typing_extensions import Self
from pydantic import Field
#from cyperf.models import LinkNameException

if "CountedFeatureStats" != "APILink":
    from cyperf.models.api_link import APILink

class CountedFeatureStats(BaseModel):
    """
    Counted feature stats.
    """ # noqa: E501
    available_count: StrictInt = Field(description="Available count.", alias="availableCount")
    consumers: List[CountedFeatureConsumer] = Field(description="Consumed by.")
    feature_name: StrictStr = Field(description="The feature name.", alias="featureName")
    installed_count: StrictInt = Field(description="Total installed count.", alias="installedCount")
    links: Optional[List[APILink]] = Field(default=None, description="Links to other properties")
#    api_client: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["availableCount", "consumers", "featureName", "installedCount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


#    @property
#    def rest_available_count(self):
#        if self.available_count is not None:
#            return self.available_count
#        field_info = self.__class__.__fields__["available_count"]
#        try:
#            self.available_count =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.available_count =  self.link_based_request("available_count", "GET", return_type="int")
#        return self.available_count
#
#    @rest_available_count.setter
#    def rest_available_count(self, value):
#        self.available_count = value

#    @property
#    def rest_consumers(self):
#        if self.consumers is not None:
#            return self.consumers
#        field_info = self.__class__.__fields__["consumers"]
#        try:
#            self.consumers =  self.link_based_request(field_info.alias, "GET", return_type="List[CountedFeatureConsumer]")
#        except LinkNameException as e:
#            self.consumers =  self.link_based_request("consumers", "GET", return_type="List[CountedFeatureConsumer]")
#        return self.consumers
#
#    @rest_consumers.setter
#    def rest_consumers(self, value):
#        self.consumers = value

#    @property
#    def rest_feature_name(self):
#        if self.feature_name is not None:
#            return self.feature_name
#        field_info = self.__class__.__fields__["feature_name"]
#        try:
#            self.feature_name =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.feature_name =  self.link_based_request("feature_name", "GET", return_type="str")
#        return self.feature_name
#
#    @rest_feature_name.setter
#    def rest_feature_name(self, value):
#        self.feature_name = value

#    @property
#    def rest_installed_count(self):
#        if self.installed_count is not None:
#            return self.installed_count
#        field_info = self.__class__.__fields__["installed_count"]
#        try:
#            self.installed_count =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.installed_count =  self.link_based_request("installed_count", "GET", return_type="int")
#        return self.installed_count
#
#    @rest_installed_count.setter
#    def rest_installed_count(self, value):
#        self.installed_count = value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CountedFeatureStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in consumers (list)
        _items = []
        if self.consumers:
            for _item in self.consumers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['consumers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CountedFeatureStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "availableCount": obj.get("availableCount"),
                        "consumers": [CountedFeatureConsumer.from_dict(_item) for _item in obj["consumers"]] if obj.get("consumers") is not None else None,
                        "featureName": obj.get("featureName"),
                        "installedCount": obj.get("installedCount")
            ,
            "links": obj.get("links")
        })
#        _obj.api_client = client
        return _obj

#    def update(self):
#        self.link_request("self", "PUT", body=self)
#
#   def link_based_request(self, link_name, method, return_type = None, body = None):
#        if self.links == None:
#           raise Exception("You must allow links to be present to use automatic retrieval functions.")
#        if link_name == 'self':
#            self_links = [link for link in self.links if link.rel == link_name]
#        else:
#            self_links = [link for link in self.links if link.rel == "child" and link.name == link_name]
#        if len(self_links) == 0:
#           raise LinkNameException(f"Missing {link_name} link.")
#        self_link = self_links[0]
#        
#        _host = None
#
#        _collection_formats: Dict[str, str] = {
#        }#
#
#        _path_params: Dict[str, str] = {}
#        _query_params: List[Tuple[str, str]] = []
#        _header_params: Dict[str, Optional[str]] = {}
#        _form_params: List[Tuple[str, str]] = []
#        _files: Dict[str, Union[str, bytes]] = {}
#        _body_params: Optional[bytes] = None
#        if body:
#            _body_params = body.to_json().encode('utf-8')
#
#        # set the HTTP header `Accept`
#        if 'Accept' not in _header_params:
#            _header_params['Accept'] = self.api_client.select_header_accept(
#                [
#                    'application/json'
#                ]
#            )
#        if 'Content-Type' not in _header_params:
#            _header_params['Content-Type'] = self.api_client.select_header_content_type(
#                [
#                    'application/json'
#                ]
#            )
#        _auth_settings: List[str] = [
#            'OAuth2',
#        ]
#        _param = self.api_client.param_serialize(
#            method=method,
#           resource_path=self_link.href,
#            path_params=_path_params,
#           query_params=_query_params,
#           body=_body_params,
#            post_params=_form_params,
#            files=_files,
#            auth_settings=_auth_settings,
#            collection_formats=_collection_formats,
#            _host=_host
#        )
#        response_data = self.api_client.call_api(
#            *_param
#        )
#        response_data.read()
#        response_types = {
#            '200': return_type,
#            '500': 'ErrorResponse'
#        }
#        return self.api_client.response_deserialize(response_data, response_types).data
    


