# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set, Union, GenericAlias, get_args
from typing_extensions import Self
from pydantic import Field
#from cyperf.models import LinkNameException

if "FeatureReservation" != "APILink":
    from cyperf.models.api_link import APILink

class FeatureReservation(BaseModel):
    """
    The reservation info.
    """ # noqa: E501
    available_count: StrictInt = Field(description="Count available for reservation.", alias="availableCount")
    is_allowed: StrictBool = Field(description="Boolean flag denoting if reservation is allowed for the feature.", alias="isAllowed")
    reserved_count: StrictInt = Field(description="The total reserved count.", alias="reservedCount")
    reserved_remaining_duration: StrictInt = Field(description="Remaining duration, in seconds, of the reservation.", alias="reservedRemainingDuration")
    links: Optional[List[APILink]] = Field(default=None, description="Links to other properties")
#    api_client: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["availableCount", "isAllowed", "reservedCount", "reservedRemainingDuration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


#    @property
#    def rest_available_count(self):
#        if self.available_count is not None:
#            return self.available_count
#        field_info = self.__class__.__fields__["available_count"]
#        try:
#            self.available_count =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.available_count =  self.link_based_request("available_count", "GET", return_type="int")
#        return self.available_count
#
#    @rest_available_count.setter
#    def rest_available_count(self, value):
#        self.available_count = value

#    @property
#    def rest_is_allowed(self):
#        if self.is_allowed is not None:
#            return self.is_allowed
#        field_info = self.__class__.__fields__["is_allowed"]
#        try:
#            self.is_allowed =  self.link_based_request(field_info.alias, "GET", return_type="bool")
#        except LinkNameException as e:
#            self.is_allowed =  self.link_based_request("is_allowed", "GET", return_type="bool")
#        return self.is_allowed
#
#    @rest_is_allowed.setter
#    def rest_is_allowed(self, value):
#        self.is_allowed = value

#    @property
#    def rest_reserved_count(self):
#        if self.reserved_count is not None:
#            return self.reserved_count
#        field_info = self.__class__.__fields__["reserved_count"]
#        try:
#            self.reserved_count =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.reserved_count =  self.link_based_request("reserved_count", "GET", return_type="int")
#        return self.reserved_count
#
#    @rest_reserved_count.setter
#    def rest_reserved_count(self, value):
#        self.reserved_count = value

#    @property
#    def rest_reserved_remaining_duration(self):
#        if self.reserved_remaining_duration is not None:
#            return self.reserved_remaining_duration
#        field_info = self.__class__.__fields__["reserved_remaining_duration"]
#        try:
#            self.reserved_remaining_duration =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.reserved_remaining_duration =  self.link_based_request("reserved_remaining_duration", "GET", return_type="int")
#        return self.reserved_remaining_duration
#
#    @rest_reserved_remaining_duration.setter
#    def rest_reserved_remaining_duration(self, value):
#        self.reserved_remaining_duration = value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureReservation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureReservation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "availableCount": obj.get("availableCount"),
                        "isAllowed": obj.get("isAllowed"),
                        "reservedCount": obj.get("reservedCount"),
                        "reservedRemainingDuration": obj.get("reservedRemainingDuration")
            ,
            "links": obj.get("links")
        })
#        _obj.api_client = client
        return _obj

#    def update(self):
#        self.link_request("self", "PUT", body=self)
#
#   def link_based_request(self, link_name, method, return_type = None, body = None):
#        if self.links == None:
#           raise Exception("You must allow links to be present to use automatic retrieval functions.")
#        if link_name == 'self':
#            self_links = [link for link in self.links if link.rel == link_name]
#        else:
#            self_links = [link for link in self.links if link.rel == "child" and link.name == link_name]
#        if len(self_links) == 0:
#           raise LinkNameException(f"Missing {link_name} link.")
#        self_link = self_links[0]
#        
#        _host = None
#
#        _collection_formats: Dict[str, str] = {
#        }#
#
#        _path_params: Dict[str, str] = {}
#        _query_params: List[Tuple[str, str]] = []
#        _header_params: Dict[str, Optional[str]] = {}
#        _form_params: List[Tuple[str, str]] = []
#        _files: Dict[str, Union[str, bytes]] = {}
#        _body_params: Optional[bytes] = None
#        if body:
#            _body_params = body.to_json().encode('utf-8')
#
#        # set the HTTP header `Accept`
#        if 'Accept' not in _header_params:
#            _header_params['Accept'] = self.api_client.select_header_accept(
#                [
#                    'application/json'
#                ]
#            )
#        if 'Content-Type' not in _header_params:
#            _header_params['Content-Type'] = self.api_client.select_header_content_type(
#                [
#                    'application/json'
#                ]
#            )
#        _auth_settings: List[str] = [
#            'OAuth2',
#        ]
#        _param = self.api_client.param_serialize(
#            method=method,
#           resource_path=self_link.href,
#            path_params=_path_params,
#           query_params=_query_params,
#           body=_body_params,
#            post_params=_form_params,
#            files=_files,
#            auth_settings=_auth_settings,
#            collection_formats=_collection_formats,
#            _host=_host
#        )
#        response_data = self.api_client.call_api(
#            *_param
#        )
#        response_data.read()
#        response_types = {
#            '200': return_type,
#            '500': 'ErrorResponse'
#        }
#        return self.api_client.response_deserialize(response_data, response_types).data
    


