# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cyperf.models.config_metadata_config_data_value import ConfigMetadataConfigDataValue
from cyperf.models.file_metadata import FileMetadata
from typing import Optional, Set, Union, GenericAlias, get_args
from typing_extensions import Self
from pydantic import Field
#from cyperf.models import LinkNameException

if "GenericFile" != "APILink":
    from cyperf.models.api_link import APILink

class GenericFile(BaseModel):
    """
    GenericFile
    """ # noqa: E501
    content: Optional[Union[StrictBytes, StrictStr]] = Field(default=None, description="The content of the file")
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the file")
    md5: Optional[StrictStr] = Field(default=None, description="The md5 value of the file")
    metadata: Optional[FileMetadata] = None
    name: Optional[StrictStr] = Field(default=None, description="The name of the file")
    options: Optional[Dict[str, ConfigMetadataConfigDataValue]] = Field(default=None, description="The characteristics of the file")
    owner: Optional[StrictStr] = Field(default=None, description="The user-visible name of the file's owner")
    owner_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the file's owner", alias="ownerId")
    reference_links: Optional[Dict[str, StrictInt]] = Field(default=None, alias="referenceLinks")
    size: Optional[StrictInt] = Field(default=None, description="The size of the file")
    type: Optional[StrictStr] = Field(default=None, description="The type of file")
    links: Optional[List[APILink]] = Field(default=None, description="Links to other properties")
#    api_client: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["content", "id", "md5", "metadata", "name", "options", "owner", "ownerId", "referenceLinks", "size", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


#    @property
#    def rest_content(self):
#        if self.content is not None:
#            return self.content
#        field_info = self.__class__.__fields__["content"]
#        try:
#            self.content =  self.link_based_request(field_info.alias, "GET", return_type="bytearray")
#        except LinkNameException as e:
#            self.content =  self.link_based_request("content", "GET", return_type="bytearray")
#        return self.content
#
#    @rest_content.setter
#    def rest_content(self, value):
#        self.content = value

#    @property
#    def rest_id(self):
#        if self.id is not None:
#            return self.id
#        field_info = self.__class__.__fields__["id"]
#        try:
#            self.id =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.id =  self.link_based_request("id", "GET", return_type="str")
#        return self.id
#
#    @rest_id.setter
#    def rest_id(self, value):
#        self.id = value

#    @property
#    def rest_md5(self):
#        if self.md5 is not None:
#            return self.md5
#        field_info = self.__class__.__fields__["md5"]
#        try:
#            self.md5 =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.md5 =  self.link_based_request("md5", "GET", return_type="str")
#        return self.md5
#
#    @rest_md5.setter
#    def rest_md5(self, value):
#        self.md5 = value

#    @property
#    def rest_metadata(self):
#        if self.metadata is not None:
#            return self.metadata
#        field_info = self.__class__.__fields__["metadata"]
#        try:
#            self.metadata =  self.link_based_request(field_info.alias, "GET", return_type="FileMetadata")
#        except LinkNameException as e:
#            self.metadata =  self.link_based_request("metadata", "GET", return_type="FileMetadata")
#        return self.metadata
#
#    @rest_metadata.setter
#    def rest_metadata(self, value):
#        self.metadata = value

#    @property
#    def rest_name(self):
#        if self.name is not None:
#            return self.name
#        field_info = self.__class__.__fields__["name"]
#        try:
#            self.name =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.name =  self.link_based_request("name", "GET", return_type="str")
#        return self.name
#
#    @rest_name.setter
#    def rest_name(self, value):
#        self.name = value

#    @property
#    def rest_options(self):
#        if self.options is not None:
#            return self.options
#        field_info = self.__class__.__fields__["options"]
#        try:
#            self.options =  self.link_based_request(field_info.alias, "GET", return_type="Dict[str, ConfigMetadataConfigDataValue]")
#        except LinkNameException as e:
#            self.options =  self.link_based_request("options", "GET", return_type="Dict[str, ConfigMetadataConfigDataValue]")
#        return self.options
#
#    @rest_options.setter
#    def rest_options(self, value):
#        self.options = value

#    @property
#    def rest_owner(self):
#        if self.owner is not None:
#            return self.owner
#        field_info = self.__class__.__fields__["owner"]
#        try:
#            self.owner =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.owner =  self.link_based_request("owner", "GET", return_type="str")
#        return self.owner
#
#    @rest_owner.setter
#    def rest_owner(self, value):
#        self.owner = value

#    @property
#    def rest_owner_id(self):
#        if self.owner_id is not None:
#            return self.owner_id
#        field_info = self.__class__.__fields__["owner_id"]
#        try:
#            self.owner_id =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.owner_id =  self.link_based_request("owner_id", "GET", return_type="str")
#        return self.owner_id
#
#    @rest_owner_id.setter
#    def rest_owner_id(self, value):
#        self.owner_id = value

#    @property
#    def rest_reference_links(self):
#        if self.reference_links is not None:
#            return self.reference_links
#        field_info = self.__class__.__fields__["reference_links"]
#        try:
#            self.reference_links =  self.link_based_request(field_info.alias, "GET", return_type="Dict[str, int]")
#        except LinkNameException as e:
#            self.reference_links =  self.link_based_request("reference_links", "GET", return_type="Dict[str, int]")
#        return self.reference_links
#
#    @rest_reference_links.setter
#    def rest_reference_links(self, value):
#        self.reference_links = value

#    @property
#    def rest_size(self):
#        if self.size is not None:
#            return self.size
#        field_info = self.__class__.__fields__["size"]
#        try:
#            self.size =  self.link_based_request(field_info.alias, "GET", return_type="int")
#        except LinkNameException as e:
#            self.size =  self.link_based_request("size", "GET", return_type="int")
#        return self.size
#
#    @rest_size.setter
#    def rest_size(self, value):
#        self.size = value

#    @property
#    def rest_type(self):
#        if self.type is not None:
#            return self.type
#        field_info = self.__class__.__fields__["type"]
#        try:
#            self.type =  self.link_based_request(field_info.alias, "GET", return_type="str")
#        except LinkNameException as e:
#            self.type =  self.link_based_request("type", "GET", return_type="str")
#        return self.type
#
#    @rest_type.setter
#    def rest_type(self, value):
#        self.type = value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenericFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "owner",
            "owner_id",
            "type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in options (dict)
        _field_dict = {}
        if self.options:
            for _key in self.options:
                if self.options[_key]:
                    _field_dict[_key] = self.options[_key].to_dict()
            _dict['options'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenericFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "content": obj.get("content"),
                        "id": obj.get("id"),
                        "md5": obj.get("md5"),
                        "metadata": FileMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
                        "name": obj.get("name"),
                        "options": dict(
                (_k, ConfigMetadataConfigDataValue.from_dict(_v))
                for _k, _v in obj["options"].items()
            )
            if obj.get("options") is not None
            else None,
                        "owner": obj.get("owner"),
                        "ownerId": obj.get("ownerId"),
                        "referenceLinks": obj.get("referenceLinks"),
                        "size": obj.get("size"),
                        "type": obj.get("type")
            ,
            "links": obj.get("links")
        })
#        _obj.api_client = client
        return _obj

#    def update(self):
#        self.link_request("self", "PUT", body=self)
#
#   def link_based_request(self, link_name, method, return_type = None, body = None):
#        if self.links == None:
#           raise Exception("You must allow links to be present to use automatic retrieval functions.")
#        if link_name == 'self':
#            self_links = [link for link in self.links if link.rel == link_name]
#        else:
#            self_links = [link for link in self.links if link.rel == "child" and link.name == link_name]
#        if len(self_links) == 0:
#           raise LinkNameException(f"Missing {link_name} link.")
#        self_link = self_links[0]
#        
#        _host = None
#
#        _collection_formats: Dict[str, str] = {
#        }#
#
#        _path_params: Dict[str, str] = {}
#        _query_params: List[Tuple[str, str]] = []
#        _header_params: Dict[str, Optional[str]] = {}
#        _form_params: List[Tuple[str, str]] = []
#        _files: Dict[str, Union[str, bytes]] = {}
#        _body_params: Optional[bytes] = None
#        if body:
#            _body_params = body.to_json().encode('utf-8')
#
#        # set the HTTP header `Accept`
#        if 'Accept' not in _header_params:
#            _header_params['Accept'] = self.api_client.select_header_accept(
#                [
#                    'application/json'
#                ]
#            )
#        if 'Content-Type' not in _header_params:
#            _header_params['Content-Type'] = self.api_client.select_header_content_type(
#                [
#                    'application/json'
#                ]
#            )
#        _auth_settings: List[str] = [
#            'OAuth2',
#        ]
#        _param = self.api_client.param_serialize(
#            method=method,
#           resource_path=self_link.href,
#            path_params=_path_params,
#           query_params=_query_params,
#           body=_body_params,
#            post_params=_form_params,
#            files=_files,
#            auth_settings=_auth_settings,
#            collection_formats=_collection_formats,
#            _host=_host
#        )
#        response_data = self.api_client.call_api(
#            *_param
#        )
#        response_data.read()
#        response_types = {
#            '200': return_type,
#            '500': 'ErrorResponse'
#        }
#        return self.api_client.response_deserialize(response_data, response_types).data
    


