# coding: utf-8

"""
    CyPerf Application API

    CyPerf REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cyperf.models.param_metadata_type_info_array_v2 import ParamMetadataTypeInfoArrayV2
from cyperf.models.param_metadata_type_info_int import ParamMetadataTypeInfoInt
from cyperf.models.param_metadata_type_info_media import ParamMetadataTypeInfoMedia
from cyperf.models.param_metadata_type_info_string import ParamMetadataTypeInfoString
from typing import Optional, Set, Union, GenericAlias, get_args
from typing_extensions import Self
from pydantic import Field
#from cyperf.models import LinkNameException

if "ParamMetadataTypeInfo" != "APILink":
    from cyperf.models.api_link import APILink

class ParamMetadataTypeInfo(BaseModel):
    """
    ParamMetadataTypeInfo
    """ # noqa: E501
    array_v2: Optional[ParamMetadataTypeInfoArrayV2] = Field(default=None, alias="arrayV2")
    int: Optional[ParamMetadataTypeInfoInt] = None
    media: Optional[ParamMetadataTypeInfoMedia] = None
    string: Optional[ParamMetadataTypeInfoString] = None
    links: Optional[List[APILink]] = Field(default=None, description="Links to other properties")
#    api_client: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["arrayV2", "int", "media", "string"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


#    @property
#    def rest_array_v2(self):
#        if self.array_v2 is not None:
#            return self.array_v2
#        field_info = self.__class__.__fields__["array_v2"]
#        try:
#            self.array_v2 =  self.link_based_request(field_info.alias, "GET", return_type="ParamMetadataTypeInfoArrayV2")
#        except LinkNameException as e:
#            self.array_v2 =  self.link_based_request("array_v2", "GET", return_type="ParamMetadataTypeInfoArrayV2")
#        return self.array_v2
#
#    @rest_array_v2.setter
#    def rest_array_v2(self, value):
#        self.array_v2 = value

#    @property
#    def rest_int(self):
#        if self.int is not None:
#            return self.int
#        field_info = self.__class__.__fields__["int"]
#        try:
#            self.int =  self.link_based_request(field_info.alias, "GET", return_type="ParamMetadataTypeInfoInt")
#        except LinkNameException as e:
#            self.int =  self.link_based_request("int", "GET", return_type="ParamMetadataTypeInfoInt")
#        return self.int
#
#    @rest_int.setter
#    def rest_int(self, value):
#        self.int = value

#    @property
#    def rest_media(self):
#        if self.media is not None:
#            return self.media
#        field_info = self.__class__.__fields__["media"]
#        try:
#            self.media =  self.link_based_request(field_info.alias, "GET", return_type="ParamMetadataTypeInfoMedia")
#        except LinkNameException as e:
#            self.media =  self.link_based_request("media", "GET", return_type="ParamMetadataTypeInfoMedia")
#        return self.media
#
#    @rest_media.setter
#    def rest_media(self, value):
#        self.media = value

#    @property
#    def rest_string(self):
#        if self.string is not None:
#            return self.string
#        field_info = self.__class__.__fields__["string"]
#        try:
#            self.string =  self.link_based_request(field_info.alias, "GET", return_type="ParamMetadataTypeInfoString")
#        except LinkNameException as e:
#            self.string =  self.link_based_request("string", "GET", return_type="ParamMetadataTypeInfoString")
#        return self.string
#
#    @rest_string.setter
#    def rest_string(self, value):
#        self.string = value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ParamMetadataTypeInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of array_v2
        if self.array_v2:
            _dict['arrayV2'] = self.array_v2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of int
        if self.int:
            _dict['int'] = self.int.to_dict()
        # override the default output from pydantic by calling `to_dict()` of media
        if self.media:
            _dict['media'] = self.media.to_dict()
        # override the default output from pydantic by calling `to_dict()` of string
        if self.string:
            _dict['string'] = self.string.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ParamMetadataTypeInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            _obj = cls.model_validate(obj)
#            _obj.api_client = client
            return _obj

        _obj = cls.model_validate({
            "arrayV2": ParamMetadataTypeInfoArrayV2.from_dict(obj["arrayV2"]) if obj.get("arrayV2") is not None else None,
                        "int": ParamMetadataTypeInfoInt.from_dict(obj["int"]) if obj.get("int") is not None else None,
                        "media": ParamMetadataTypeInfoMedia.from_dict(obj["media"]) if obj.get("media") is not None else None,
                        "string": ParamMetadataTypeInfoString.from_dict(obj["string"]) if obj.get("string") is not None else None
            ,
            "links": obj.get("links")
        })
#        _obj.api_client = client
        return _obj

#    def update(self):
#        self.link_request("self", "PUT", body=self)
#
#   def link_based_request(self, link_name, method, return_type = None, body = None):
#        if self.links == None:
#           raise Exception("You must allow links to be present to use automatic retrieval functions.")
#        if link_name == 'self':
#            self_links = [link for link in self.links if link.rel == link_name]
#        else:
#            self_links = [link for link in self.links if link.rel == "child" and link.name == link_name]
#        if len(self_links) == 0:
#           raise LinkNameException(f"Missing {link_name} link.")
#        self_link = self_links[0]
#        
#        _host = None
#
#        _collection_formats: Dict[str, str] = {
#        }#
#
#        _path_params: Dict[str, str] = {}
#        _query_params: List[Tuple[str, str]] = []
#        _header_params: Dict[str, Optional[str]] = {}
#        _form_params: List[Tuple[str, str]] = []
#        _files: Dict[str, Union[str, bytes]] = {}
#        _body_params: Optional[bytes] = None
#        if body:
#            _body_params = body.to_json().encode('utf-8')
#
#        # set the HTTP header `Accept`
#        if 'Accept' not in _header_params:
#            _header_params['Accept'] = self.api_client.select_header_accept(
#                [
#                    'application/json'
#                ]
#            )
#        if 'Content-Type' not in _header_params:
#            _header_params['Content-Type'] = self.api_client.select_header_content_type(
#                [
#                    'application/json'
#                ]
#            )
#        _auth_settings: List[str] = [
#            'OAuth2',
#        ]
#        _param = self.api_client.param_serialize(
#            method=method,
#           resource_path=self_link.href,
#            path_params=_path_params,
#           query_params=_query_params,
#           body=_body_params,
#            post_params=_form_params,
#            files=_files,
#            auth_settings=_auth_settings,
#            collection_formats=_collection_formats,
#            _host=_host
#        )
#        response_data = self.api_client.call_api(
#            *_param
#        )
#        response_data.read()
#        response_types = {
#            '200': return_type,
#            '500': 'ErrorResponse'
#        }
#        return self.api_client.response_deserialize(response_data, response_types).data
    


